### ISSUE TITLE
Submenu items don't work on header menu

### ISSUE THREAD

**Issue by sarah-savage** [aspirepress/site-theme#19]
When adding a submenu item, the entire menu breaks. We should make it possible to add these submenu items so that we can stop expanding the menu size infinitely as we add new pages.

**Comment by verlev** [comment]
If it's too much work to fix in this version (submenus & mobile menus can be quite hard to get right and accessible), maybe move submenus as a 'must have' for the re-designed website?

(not all extra pages may need to be in the menu, we could work with simple ul's on top of subsection pages)

_atm, Get Involved and Join the community could maybe be merged (by adding 2nd section with h2#slack on Get involved + a redirect on the current https://aspirepress.org/slack/ to https://aspirepress.org/get-involved/#slack_

**Comment by kylek14** [comment]
This is fixed in a local dev version, will merge with the Main branch this evening.
